### ISSUE TITLE
Require whisper install

### ISSUE THREAD

**Issue by jbussdieker** [jbussdieker/puppet-carbon#6]
Need to make daemons depend on whisper somehow.

`````
Execution of '/etc/init.d/carbon-cache-a start' returned 1:
 * Starting carbon cache
 Traceback (most recent call last):
 File "/opt/graphite/bin/carbon-cache.py", line 32, in <module> run_twistd_plugin(__file__)
 File "/opt/graphite/lib/carbon/util.py", line 32, in run_twistd_plugin from carbon.conf import get_parser
 File "/opt/graphite/lib/carbon/conf.py", line 24, in <module> import whisper ImportError: No module named whisper ...fail! 
`````

**Comment by jbussdieker** [comment]
Fixed at 92dfc3daef3720f8a40f2479a35d31ae44dcc2af

**Comment by daks** [comment]
Hello,
does it means that this module can't be used only for carbon usage? I want to install only carbon to do routing between two carbon+whisper instances.

**Comment by jbussdieker** [comment]
Hmm good point. I suppose that logic makes more sense in the carbon cache.
